<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anant" failures="5" tests="31" name="EDGE Standard Tests" time="854.96" errors="0" timestamp="2025-10-03T23:55:42 IST">
  <testcase classname="com.sauceDemo.testCases.TC001_LoginTest" name="testSuccessfulLoginUser" time="12.584"/>
  <testcase classname="com.sauceDemo.testCases.TC001_LoginTest" name="testLoginProblemUser" time="11.973"/>
  <testcase classname="com.sauceDemo.testCases.TC001_LoginTest" name="testLoginPerformanceGlitchUser" time="17.063"/>
  <testcase classname="com.sauceDemo.testCases.TC002_ProductTest" name="testAddSingleProductToCart" time="0.644"/>
  <testcase classname="com.sauceDemo.testCases.TC002_ProductTest" name="testAddMultipleProductsToCart" time="0.582"/>
  <testcase classname="com.sauceDemo.testCases.TC003_CheckoutTest" name="testSuccessfulProductCheckout" time="42.932"/>
  <testcase classname="com.sauceDemo.testCases.TC003_CheckoutTest" name="testCancelCheckoutFromInformationPage" time="20.88"/>
  <testcase classname="com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest" name="testInvalidLoginForScreenshot" time="2.102">
    <skipped/>
  </testcase> <!-- testInvalidLoginForScreenshot -->
  <testcase classname="com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest" name="testInvalidLoginForScreenshot" time="1.85">
    <failure type="java.lang.AssertionError" message="Error message for invalid login is incorrect. expected [Epic sadface: This is an incorrect error message to force failure] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: Error message for invalid login is incorrect. expected [Epic sadface: This is an incorrect error message to force failure] but found [Epic sadface: Username and password do not match any user in this service]
at com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest.testInvalidLoginForScreenshot(TC004_FailedLoginScreenshotTest.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidLoginForScreenshot -->
  <testcase classname="com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest" name="testLockedOutUserLoginForScreenshot" time="1.968">
    <skipped/>
  </testcase> <!-- testLockedOutUserLoginForScreenshot -->
  <testcase classname="com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest" name="testLockedOutUserLoginForScreenshot" time="1.796">
    <failure type="java.lang.AssertionError" message="Error message for locked out user is incorrect. expected [Epic sadface: Intentional wrong message for screenshot] but found [Epic sadface: Sorry, this user has been locked out.]">
      <![CDATA[java.lang.AssertionError: Error message for locked out user is incorrect. expected [Epic sadface: Intentional wrong message for screenshot] but found [Epic sadface: Sorry, this user has been locked out.]
at com.sauceDemo.testCases.TC004_FailedLoginScreenshotTest.testLockedOutUserLoginForScreenshot(TC004_FailedLoginScreenshotTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testLockedOutUserLoginForScreenshot -->
  <testcase classname="com.sauceDemo.testCases.TC005_RetryAnalyzerTest" name="testFlakyLoginAttempt" time="12.015">
    <skipped/>
  </testcase> <!-- testFlakyLoginAttempt -->
  <testcase classname="com.sauceDemo.testCases.TC005_RetryAnalyzerTest" name="testFlakyLoginAttempt" time="12.019">
    <failure type="java.lang.AssertionError" message="Simulating a transient failure. This test should be retried!">
      <![CDATA[java.lang.AssertionError: Simulating a transient failure. This test should be retried!
at com.sauceDemo.testCases.TC005_RetryAnalyzerTest.testFlakyLoginAttempt(TC005_RetryAnalyzerTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testFlakyLoginAttempt -->
  <testcase classname="com.sauceDemo.testCases.TC006_LoginDDTTest" name="testLoginDataDrivenTest" time="11.895"/>
  <testcase classname="com.sauceDemo.testCases.TC006_LoginDDTTest" name="testLoginDataDrivenTest" time="1.852"/>
  <testcase classname="com.sauceDemo.testCases.TC006_LoginDDTTest" name="testLoginDataDrivenTest" time="12.067"/>
  <testcase classname="com.sauceDemo.testCases.TC006_LoginDDTTest" name="testLoginDataDrivenTest" time="16.968"/>
  <testcase classname="com.sauceDemo.testCases.TC006_LoginDDTTest" name="testLoginDataDrivenTest" time="1.965"/>
  <testcase classname="com.sauceDemo.testCases.TC007_DashboardMenuTest" name="verifyHamburgerMenuItems" time="13.272"/>
  <testcase classname="com.sauceDemo.testCases.TC008_PurchaseFlowJson" name="verifyPurchaseFlowWithDynamicData" time="46.033"/>
  <testcase classname="com.sauceDemo.testCases.TC008_PurchaseFlowJson" name="verifyPurchaseFlowWithDynamicData" time="44.408"/>
  <testcase classname="com.sauceDemo.testCases.TC008_PurchaseFlowJson" name="verifyPurchaseFlowWithDynamicData" time="24.454"/>
  <testcase classname="com.sauceDemo.testCases.TC008_PurchaseFlowJson" name="verifyPurchaseFlowWithDynamicData" time="63.781">
    <skipped/>
  </testcase> <!-- verifyPurchaseFlowWithDynamicData -->
  <testcase classname="com.sauceDemo.testCases.TC008_PurchaseFlowJson" name="verifyPurchaseFlowWithDynamicData" time="63.84">
    <failure type="java.lang.AssertionError" message="Error message should be displayed. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error message should be displayed. expected [true] but found [false]
at com.sauceDemo.testCases.TC008_PurchaseFlowJson.verifyPurchaseFlowWithDynamicData(TC008_PurchaseFlowJson.java:138)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyPurchaseFlowWithDynamicData -->
  <testcase classname="com.sauceDemo.testCases.TC009_DynamicCheckoutInfoTest" name="verifyPurchaseFlowWithFakerData" time="66.078"/>
  <testcase classname="com.sauceDemo.testCases.TC010_BuilderPatternCheckoutTest" name="tc010_verifyPurchaseFlowWithBuilderData" time="54.361"/>
  <testcase classname="com.sauceDemo.testCases.TC011_CustomExceptionDemoTest" name="demonstrateCustomExceptions" time="22.439">
    <skipped/>
  </testcase> <!-- demonstrateCustomExceptions -->
  <testcase classname="com.sauceDemo.testCases.TC011_CustomExceptionDemoTest" name="demonstrateCustomExceptions" time="21.996">
    <failure type="com.sauceDemo.exceptions.ElementNotFoundException" message="Failed to find expected element with ID &amp;apos;nonExistentElementID123&amp;apos; on the Products Page. This element is critical for the test flow.">
      <![CDATA[com.sauceDemo.exceptions.ElementNotFoundException: Failed to find expected element with ID 'nonExistentElementID123' on the Products Page. This element is critical for the test flow.
at com.sauceDemo.testCases.TC011_CustomExceptionDemoTest.demonstrateCustomExceptions(TC011_CustomExceptionDemoTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#nonExistentElementID123"}
  (Session info: chrome=140.0.7339.208)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.15.0', revision: '1d14b5521b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.13'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [7df47d3586c638c0afbf8a303477f026, findElement {using=id, value=nonExistentElementID123}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 140.0.7339.208, chrome: {chromedriverVersion: 140.0.7339.207 (17230b545fd..., userDataDir: C:\Users\anant\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50260}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50260/devtoo..., se:cdpVersion: 140.0.7339.208, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 7df47d3586c638c0afbf8a303477f026
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:200)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:175)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:607)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:364)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
at com.sauceDemo.testCases.TC011_CustomExceptionDemoTest.demonstrateCustomExceptions(TC011_CustomExceptionDemoTest.java:48)
... 27 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- demonstrateCustomExceptions -->
  <testcase classname="com.sauceDemo.testCases.TC012_WebDriverUtilsDemoTest" name="demonstrateWebDriverUtils" time="34.078"/>
  <testcase classname="com.sauceDemo.testCases.TC013_HyundaiWarrantyWindowHandling" name="testHyundaiWarrantyLinkWindowHandling" time="41.899"/>
  <testcase classname="com.sauceDemo.testCases.TC014_EnhancedLoginTest" name="testEnhancedLogin" time="1.892"/>
</testsuite> <!-- EDGE Standard Tests -->
